myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"#is used to create a namespace\

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name="home"),
    path('fact/<n>',views.fact,name="fact"),
    #path("secondarysuffix",address of function,name of mapping)
    path('child/',views.child,name="child"),
]

p6/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/',views.sample,name="sample"),
    #path('primmary suffix,include("appname.urls"))
    path('myapp/',include("myapp.urls")),

]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from math import factorial
# Create your views here.

def index(request):
    return HttpResponse("<h1>welcome to views of an app</h1>")

def home(request):
    return render(request,"myapp/home.html",{'name':"Ranga"})

def fact(request,n):
    n=int(n)
    return HttpResponse("<h4>factorial is {}</h4>".format(factorial(n)))

def child(request):
    return render(request,"child.html")

def sam(request):
    return render(request,"myapp/sample.html")

templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE HTML FILE</title>
    {% endblock %}
</head>

<body>
    <h1>Navbar</h1>
    {% block content %}
    <h1>Welcome to Base.html</h1> 
    {% endblock %}
    

</body>

</html>

templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>html demo</title>
</head>
<body>
    <h2>welcome to html page</h2>
    <h3>{{name}}</h3>
    <a href="{% url 'myapp:child' %}">Child</a>
    <a href="{% url 'sample' %}">sample</a>

</body>
</html>

templates/myapp/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>welcome to sample</title>
</head>
<body>
    <h1>welcome to sam.html</h1>
    <a href="{% url 'myapp:child' %}">Child</a>
    <a href="{% url 'myapp:home' %}">Home</a>
</body>
</html>